# Generated by Django 5.2.1 on 2025-05-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('hepatitis_b_stage', models.CharField(choices=[('acute', 'Acute'), ('chronic', 'Chronic')], default='acute', max_length=7)),
                ('treatment_status', models.CharField(choices=[('ongoing', 'On going'), ('completed', 'Completed'), ('followup', 'Follow up')], default='ongoing', max_length=20)),
                ('treatment_type', models.CharField(blank=True, max_length=100)),
                ('vaccination_status', models.BooleanField(default=False)),
                ('comorbidities', models.TextField(blank=True)),
                ('region', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
