# Generated by Django 5.2.1 on 2025-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='facility',
            field=models.CharField(blank=True, null=True),
        ),
    ]
